### ISSUE TITLE
Colors are off in mcedit

### ISSUE THREAD

**Issue by diver-ua** [DeadNews/mc-onedark#10]
Hi! It's awesome theme you have here. There's only one catch: colors (and background) in mcedit are off...:
![image](https://github.com/DeadNews/mc-onedark/assets/58228615/3a1c4fd5-973e-4c12-a2b5-10613b5e7a06)

Maybe, this micro-patch will help:
```
--- a/onedark16M.ini
+++ b/onedark16M.ini
@@ -121,14 +121,14 @@
 helptitle = yellow;background
 
 [editor]
-_default_ = lightgray;background
+_default_ = lightgray;#282c34
 editbold = white;gray
 editmarked = white;gray
-editwhitespace = gray;background
+editwhitespace = gray;#282c34
 editlinestate = white;cyan
 bookmark = white;red
 bookmarkfound = white;gray
-editrightmargin = brightblue;background
+editrightmargin = brightblue;#282c34
 # editbg =
 editframe = gray;
 editframeactive = white;
```
After applying, editor looks like this:
![image](https://github.com/DeadNews/mc-onedark/assets/58228615/495f60d8-529b-4cd1-b8c4-ec053cbbe362)

**Comment by deadnews** [comment]
@diver-ua
Thank you for your suggestion, but I can't reproduce it.

```console
$ mcedit --version                                                                                                                                                                                          
GNU Midnight Commander 4.8.30
Built with GLib 2.76.4
Built with S-Lang 2.3.3 with terminfo database
Built with libssh2 1.11.0
With builtin Editor and Aspell support
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish
Data types:
char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64;
```

I initially don't have this problem:
![Screenshot_1](https://github.com/DeadNews/mc-onedark/assets/8158661/ce0996ce-c866-477a-a5bd-54b4fd7e7cbb)

I can't help but notice that you replace `background` with `#282c34`, but `background` is an alias of `#282c34`:
https://github.com/DeadNews/mc-onedark/blob/07e8704d38fe792c285c8c23c837b6e1872a7015/skins/onedark16M.ini#L46
